/// Flutter icons AtivitiIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AtivitiIcons
///      fonts:
///       - asset: fonts/AtivitiIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AtivitiIcons {
  AtivitiIcons._();

  static const _kFontFam = 'AtivitiIcons';

  static const IconData plus = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData print = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData profile = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData profileactive = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData qr = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData qractive = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData radioon = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData reset = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData search = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData shape_2_ = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData share = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData shower = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData snacks = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData sort = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData star = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData staractive = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData switchoff = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData switchon = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData tag = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData time__2_ = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData time = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData timespeed = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData toilets = const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData userprofile = const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData validate = const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData warning = const IconData(0xe819, fontFamily: _kFontFam);
  static const IconData water = const IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData wifi = const IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData wrong = const IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData agenda = const IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData agendaactive = const IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData airconditioner = const IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData alarm = const IconData(0xe820, fontFamily: _kFontFam);
  static const IconData arrow = const IconData(0xe821, fontFamily: _kFontFam);
  static const IconData arrow_base = const IconData(0xe822, fontFamily: _kFontFam);
  static const IconData arrowlarge = const IconData(0xe823, fontFamily: _kFontFam);
  static const IconData calendar = const IconData(0xe824, fontFamily: _kFontFam);
  static const IconData camera = const IconData(0xe825, fontFamily: _kFontFam);
  static const IconData cancel = const IconData(0xe826, fontFamily: _kFontFam);
  static const IconData cart = const IconData(0xe827, fontFamily: _kFontFam);
  static const IconData caseoff__2_ = const IconData(0xe828, fontFamily: _kFontFam);
  static const IconData caseoff = const IconData(0xe829, fontFamily: _kFontFam);
  static const IconData caseon = const IconData(0xe82a, fontFamily: _kFontFam);
  static const IconData changingrooms = const IconData(0xe82b, fontFamily: _kFontFam);
  static const IconData checkcircle = const IconData(0xe82c, fontFamily: _kFontFam);
  static const IconData close = const IconData(0xe82d, fontFamily: _kFontFam);
  static const IconData closecircle = const IconData(0xe82e, fontFamily: _kFontFam);
  static const IconData coffee = const IconData(0xe82f, fontFamily: _kFontFam);
  static const IconData condition = const IconData(0xe830, fontFamily: _kFontFam);
  static const IconData delete = const IconData(0xe831, fontFamily: _kFontFam);
  static const IconData disableaccess = const IconData(0xe832, fontFamily: _kFontFam);
  static const IconData downloads = const IconData(0xe833, fontFamily: _kFontFam);
  static const IconData drinks = const IconData(0xe834, fontFamily: _kFontFam);
  static const IconData edit = const IconData(0xe835, fontFamily: _kFontFam);
  static const IconData england = const IconData(0xe836, fontFamily: _kFontFam);
  static const IconData explorer = const IconData(0xe837, fontFamily: _kFontFam);
  static const IconData exploreractive = const IconData(0xe838, fontFamily: _kFontFam);
  static const IconData eyehide = const IconData(0xe839, fontFamily: _kFontFam);
  static const IconData eyeshow = const IconData(0xe83a, fontFamily: _kFontFam);
  static const IconData facebook = const IconData(0xe83b, fontFamily: _kFontFam);
  static const IconData feeds = const IconData(0xe83c, fontFamily: _kFontFam);
  static const IconData feedsactive = const IconData(0xe83d, fontFamily: _kFontFam);
  static const IconData filter = const IconData(0xe83e, fontFamily: _kFontFam);
  static const IconData france = const IconData(0xe83f, fontFamily: _kFontFam);
  static const IconData geolocalisation = const IconData(0xe840, fontFamily: _kFontFam);
  static const IconData geolocalisationcenter = const IconData(0xe841, fontFamily: _kFontFam);
  static const IconData getdirection = const IconData(0xe842, fontFamily: _kFontFam);
  static const IconData google = const IconData(0xe843, fontFamily: _kFontFam);
  static const IconData group__2_ = const IconData(0xe844, fontFamily: _kFontFam);
  static const IconData group = const IconData(0xe845, fontFamily: _kFontFam);
  static const IconData heart = const IconData(0xe846, fontFamily: _kFontFam);
  static const IconData heartactive = const IconData(0xe847, fontFamily: _kFontFam);
  static const IconData homeactive = const IconData(0xe848, fontFamily: _kFontFam);
  static const IconData iconsbar = const IconData(0xe849, fontFamily: _kFontFam);
  static const IconData icons_time_speed = const IconData(0xe84a, fontFamily: _kFontFam);
  static const IconData img = const IconData(0xe84b, fontFamily: _kFontFam);
  static const IconData info = const IconData(0xe84c, fontFamily: _kFontFam);
  static const IconData level = const IconData(0xe84d, fontFamily: _kFontFam);
  static const IconData list = const IconData(0xe84e, fontFamily: _kFontFam);
  static const IconData littlearrowleft = const IconData(0xe84f, fontFamily: _kFontFam);
  static const IconData location_1_ = const IconData(0xe850, fontFamily: _kFontFam);
  static const IconData location_2_ = const IconData(0xe851, fontFamily: _kFontFam);
  static const IconData location = const IconData(0xe852, fontFamily: _kFontFam);
  static const IconData lock = const IconData(0xe853, fontFamily: _kFontFam);
  static const IconData lockers = const IconData(0xe854, fontFamily: _kFontFam);
  static const IconData logout = const IconData(0xe855, fontFamily: _kFontFam);
  static const IconData mail = const IconData(0xe856, fontFamily: _kFontFam);
  static const IconData map = const IconData(0xe857, fontFamily: _kFontFam);
  static const IconData menu = const IconData(0xe858, fontFamily: _kFontFam);
  static const IconData minus = const IconData(0xe859, fontFamily: _kFontFam);
  static const IconData nursery = const IconData(0xe85a, fontFamily: _kFontFam);
  static const IconData oval = const IconData(0xe85b, fontFamily: _kFontFam);
  static const IconData parking = const IconData(0xe85c, fontFamily: _kFontFam);
  static const IconData phone = const IconData(0xe85d, fontFamily: _kFontFam);
}
